services:
  db:
    image: postgres:18-alpine
    container_name: busiq_db
    environment:
      POSTGRES_DB: busiq
      POSTGRES_USER: busiq_manager
      POSTGRES_PASSWORD: Minestadion#2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: busiq_app
    depends_on:
      - db
    volumes:
      - ./data/gtfs:/app/data/gtfs
    ports:
      - "8080:8080"

volumes:
  pgdata: